# Generated by Django 4.2.21 on 2025-08-06 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='连接名称')),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('oracle', 'Oracle')], max_length=20, verbose_name='数据库类型')),
                ('host', models.CharField(max_length=255, verbose_name='主机地址')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('database', models.CharField(max_length=100, verbose_name='数据库名称')),
                ('timeout', models.IntegerField(default=30, verbose_name='查询超时时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据库连接',
                'verbose_name_plural': '数据库连接',
            },
        ),
        migrations.CreateModel(
            name='SQLParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='参数描述')),
                ('python_code', models.TextField(verbose_name='Python代码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'SQL参数',
                'verbose_name_plural': 'SQL参数',
            },
        ),
        migrations.CreateModel(
            name='QueryInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='查询名称')),
                ('sql_template', models.TextField(verbose_name='SQL模板')),
                ('result_table', models.CharField(max_length=100, verbose_name='结果表名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbquery.databaseconnection', verbose_name='数据库连接')),
                ('parameters', models.ManyToManyField(blank=True, related_name='query_instances', to='dbquery.sqlparameter', verbose_name='参数')),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask', verbose_name='定时任务')),
            ],
            options={
                'verbose_name': '查询实例',
                'verbose_name_plural': '查询实例',
            },
        ),
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='执行状态')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='结果数据')),
                ('execution_time', models.FloatField(verbose_name='执行时间(秒)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('query_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dbquery.queryinstance', verbose_name='查询实例')),
            ],
            options={
                'verbose_name': '执行结果',
                'verbose_name_plural': '执行结果',
                'ordering': ['-created_at'],
            },
        ),
    ]
