# Generated by Django 4.2.21 on 2025-08-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbquery', '0002_remove_queryinstance_result_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionresult',
            name='rendered_sql',
            field=models.TextField(blank=True, null=True, verbose_name='解析后的SQL'),
        ),
    ]
