# Generated by Django 4.2.21 on 2025-08-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbquery', '0003_executionresult_rendered_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('oracle', 'Oracle'), ('postgresql', 'PostgreSQL')], max_length=20, verbose_name='数据库类型'),
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', '电子邮件'), ('sms', '短信'), ('webhook', 'Webhook')], max_length=20)),
                ('recipient', models.CharField(help_text='接收人信息，如邮箱、手机号或Webhook URL', max_length=255)),
                ('trigger_on_success', models.BooleanField(default=True)),
                ('trigger_on_failure', models.BooleanField(default=False)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dbquery.queryinstance')),
            ],
            options={
                'verbose_name': '通知配置',
                'verbose_name_plural': '通知管理',
            },
        ),
    ]
