# Generated by Django 4.2.21 on 2025-08-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbquery', '0004_alter_databaseconnection_db_type_notificationconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationConfig',
        ),
    ]
