# Generated by Django 4.2.21 on 2025-08-13 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('dbquery', '0005_delete_notificationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='脚本名称')),
                ('python_code', models.TextField(verbose_name='Python脚本代码')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='脚本描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scripts', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask', verbose_name='定时任务')),
            ],
            options={
                'verbose_name': '脚本执行',
                'verbose_name_plural': '脚本执行',
            },
        ),
        migrations.CreateModel(
            name='ScriptExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='执行状态')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='结果数据')),
                ('execution_time', models.FloatField(verbose_name='执行时间(秒)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('script_name', models.CharField(max_length=255, verbose_name='脚本名称')),
                ('script_content', models.TextField(verbose_name='脚本内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dbquery.scriptexecution', verbose_name='脚本')),
            ],
            options={
                'verbose_name': '脚本执行',
                'verbose_name_plural': '脚本执行',
                'ordering': ['-created_at'],
            },
        ),
    ]
