# Generated by Django 4.2.21 on 2025-08-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbquery', '0006_scriptexecution_scriptexecutionresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptexecutionresult',
            options={'ordering': ['-created_at'], 'verbose_name': '脚本执行结果', 'verbose_name_plural': '脚本执行结果'},
        ),
    ]
