# Generated by Django 4.2.21 on 2025-08-13 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbquery', '0007_alter_scriptexecutionresult_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptexecution',
            options={'permissions': [('can_execute_script', '可以执行脚本'), ('can_review_script', '可以审批脚本')]},
        ),
        migrations.RemoveField(
            model_name='scriptexecution',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='scriptexecution',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='scriptexecution',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scriptexecution',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scriptexecution',
            name='periodic_task',
        ),
        migrations.RemoveField(
            model_name='scriptexecution',
            name='python_code',
        ),
        migrations.RemoveField(
            model_name='scriptexecution',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='code',
            field=models.TextField(default=1, verbose_name='Python 代码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_scripts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='error',
            field=models.TextField(blank=True, verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='output',
            field=models.TextField(blank=True, verbose_name='执行结果'),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='脚本名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scriptexecution',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='ScriptExecutionResult',
        ),
    ]
