# Generated by Django 4.2.21 on 2025-08-13 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbquery', '0008_alter_scriptexecution_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('output', models.TextField()),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='draft', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('review_script', '可以审批脚本'), ('execute_script', '可以执行脚本'), ('change_any_script', '可以修改任何状态的脚本'), ('create_scheduled_task', '可以创建定时任务')],
            },
        ),
        migrations.DeleteModel(
            name='ScriptExecution',
        ),
        migrations.AddField(
            model_name='executionlog',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbquery.script'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
