# Generated by Django 4.2.21 on 2025-08-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbquery', '0009_executionlog_script_delete_scriptexecution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executionlog',
            options={'permissions': [('review_script', '可以审批脚本'), ('execute_script', '可以执行脚本'), ('change_any_script', '可以修改任何状态的脚本'), ('create_scheduled_task', '可以创建定时任务')], 'verbose_name': '脚本执行日志', 'verbose_name_plural': '脚本执行日志'},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'permissions': [('review_script', '可以审批脚本'), ('execute_script', '可以执行脚本'), ('change_any_script', '可以修改任何状态的脚本'), ('create_scheduled_task', '可以创建定时任务')], 'verbose_name': '脚本管理', 'verbose_name_plural': '脚本管理'},
        ),
        migrations.AlterField(
            model_name='script',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('submitted', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='draft', max_length=20),
        ),
    ]
