# Generated by Django 4.2.21 on 2025-08-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbquery', '0010_alter_executionlog_options_alter_script_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executionlog',
            options={'verbose_name': '脚本执行日志', 'verbose_name_plural': '脚本执行日志'},
        ),
    ]
