# Generated by Django 4.2.21 on 2025-08-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbquery', '0011_alter_executionlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述信息'),
        ),
        migrations.AlterField(
            model_name='script',
            name='title',
            field=models.CharField(max_length=100, verbose_name='脚本名称'),
        ),
    ]
