# Generated by Django 4.2.21 on 2025-08-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbquery', '0012_script_description_alter_script_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='code',
            field=models.TextField(verbose_name='脚本内容'),
        ),
    ]
