# Generated by Django 4.2.21 on 2025-08-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='创建IP'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_by',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='创建IP'),
        ),
    ]
