# Generated by Django 4.2.21 on 2025-08-20 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, verbose_name='规则描述')),
                ('url_pattern', models.CharField(help_text='支持正则表达式，如 ^/api/.* 或精确路径 /api/users/', max_length=200, verbose_name='URL模式')),
                ('methods', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('ALL', 'ALL')], default='ALL', max_length=10, verbose_name='HTTP方法')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('require_login', models.BooleanField(default=True, verbose_name='需要登录')),
                ('require_permission', models.BooleanField(default=False, verbose_name='需要特定权限')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('custom_response', models.JSONField(blank=True, default=dict, help_text='JSON格式，如 {"message": "自定义错误消息", "code": 403}', verbose_name='自定义响应')),
                ('priority', models.IntegerField(default=0, help_text='数字越小优先级越高，0为默认优先级', verbose_name='优先级')),
                ('allowed_groups', models.ManyToManyField(blank=True, to='auth.group', verbose_name='允许的用户组')),
                ('allowed_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='允许的用户')),
            ],
            options={
                'verbose_name': '访问控制规则',
                'verbose_name_plural': '访问控制规则',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
