# Generated by Django 4.2.21 on 2025-08-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_auto_20250820_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrolrule',
            name='match_type',
            field=models.CharField(choices=[('regex', '正则表达式'), ('exact', '精确匹配'), ('startswith', '开头匹配'), ('endswith', '结尾匹配'), ('contains', '包含')], default='regex', max_length=10, verbose_name='匹配类型'),
        ),
    ]
